name: Daily Slack Notification

on:
  schedule:
    - cron: " "
  workflow_dispatch:

jobs:
  daily-slack-notification:
    name: Send Notification to Slack
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Python Script
        run: python scripts/daily_slack.py
